version: '2.1'

services:
  monaize_core:
    extends:
      file: ../mainnet/docker-compose.yml
      service: komodo-core
    image: monaize/komodo-ac:latest
    environment:
      - AC_NAME=TESTMNZ
    command:
      -printtoconsole=1
      -txindex=1
      -rpcuser=test
      -rpcpassword=net
      -ac_supply=257142857
      -gen=1
    volumes:
      - testmonaize-data:/home/komodo/.komodo
      - zcash-params:/home/komodo/.zcash-params


  monaize_core_peer:
    extends:
      file: ../mainnet/docker-compose.yml
      service: komodo-core
    image: monaize/komodo-ac:latest
    networks:
      - rpc
    ports:
      - 10783
    environment:
      - AC_NAME=TESTMNZ
    command:
      -printtoconsole=1
      -ac_supply=257142857
      -txindex=1
      -server=1
      -rpcuser=test
      -rpcpassword=net
      -rpcallowip=172.0.0.0/8
      -rpcport=10783
      -addnode=komodocore
    volumes:
      - testmonaize-peer-data:/home/komodo/.komodo
      - zcash-params:/home/komodo/.zcash-params


  electrum:
    image: monaize/electrumx:latest
    networks:
      - rpc
      - ext
    ports:
      - 50001
      - 50002
    environment:
      - DAEMON_URL=http://test:net@monaize_core_peer:10783/
      - TCP_PORT=50001
      - SSL_PORT=50002
      - RPC_PORT=8000
      - COIN=TestKomodo
    volumes:
      - electrumx-testmonaize-data:/data

volumes:
  testmonaize-data:
  testmonaize-peer-data:
  electrumx-testmonaize-data:
  zcash-params:
    external: true

networks:
  ext:
    external: true
  p2p:
  rpc: