version: '2.1'

services:
  monaize-core:
    networks:
      - testmnz_rpc
    image: monaize/komodo-ac:latest
    environment:
      - AC_NAME=TESTMNZ
    command:
      -printtoconsole=1
      -txindex=1
      -server=1
      -rpcuser=test
      -rpcpassword=net
      -rpcallowip=172.0.0.0/8
      -rpcport=13353
      -ac_supply=257142857
      -addnode=51.15.54.2
    volumes:
      - testmonaize-data:/home/komodo/.komodo
      - zcash-params:/home/komodo/.zcash-params

volumes:
  testmonaize-data:
  zcash-params:
    external: true

networks:
  testmnz_rpc:
    external: true
