version: '2.1'

services:
  mnz_explorer:
    image: monaize/rpc-explorer:0.1
    networks:
      - testmnz_rpc
      - traefik
    # ports:
    #   - 3002
    environment:
      - COIN=TESTMNZ
      - RPC_PORT=13353
      - RPC_HOST=monaize-core
      - DEBUG=*
    labels:
      - "traefik.backend=mnz-explorer"
      - "traefik.docker.network=traefik"
      - "traefik.port=3002"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host: mnz.explorer.monaize.com"

networks:
  testmnz_rpc:
    external: true
  traefik:
    external: true
