version: '2.1'

services:
  electrum:
    image: monaize/electrumx:latest
    networks:
      - testmnz_rpc
    ports:
      - 10002:50001
      - 20002:50002
    environment:
      - DAEMON_URL=http://test:net@monaize-core:13353/
      - TCP_PORT=50001
      - SSL_PORT=50002
      - RPC_PORT=8000
      - COIN=TestMonaize
    volumes:
      - electrumx-testmonaize-data:/data

volumes:
  electrumx-testmonaize-data:

networks:
  testmnz_rpc:
    external: true
