version: '2.1'

services:
  komodo_core:
    networks:
      - testkmd_rpc
    image: monaize/komodo-ac:latest
    environment:
      - AC_NAME=TESTKMD
    command:
      -printtoconsole=1
      -txindex=1
      -server=1
      -rpcuser=test
      -rpcpassword=net
      -rpcallowip=172.0.0.0/8
      -rpcport=10783
      -ac_supply=257142857
      -addnode=51.15.54.2
    volumes:
      - testkomodo-data:/home/komodo/.komodo
      - zcash-params:/home/komodo/.zcash-params

volumes:
  testkomodo-data:
  zcash-params:
    external: true

networks:
  testkmd_rpc:
    external: true