version: '2.1'

services:
  komodo-core:
    networks:
      - rpc
    image: monaize/komodo-ac:latest
    environment:
      - AC_NAME=TESTKMD
    command:
      -printtoconsole=1
      -txindex=1
      -server=1
      -rpcuser=test
      -rpcpassword=net
      -rpcallowip=172.0.0.0/8
      -rpcport=10783
      -ac_supply=257142857
      -addnode=51.15.54.2
    volumes:
      - testkomodo-data:/home/komodo/.komodo
      - zcash-params:/home/komodo/.zcash-params

  electrum:
    image: monaize/electrumx:latest
    networks:
      - rpc
    ports:
      - 50001
      - 50002
    environment:
      - DAEMON_URL=http://test:net@komodo-core:10783/
      - TCP_PORT=50001
      - SSL_PORT=50002
      - RPC_PORT=8000
      - COIN=TestKomodo
    volumes:
      - electrumx-testkomodo-data:/data

volumes:
  testkomodo-data:
  electrumx-testkomodo-data:
  zcash-params:
    external: true

networks:
  rpc: