version: '2.1'

services:
  komodo-core:
    extends:
      file: ../mainnet/docker-compose.yml
      service: komodo-core
    image: monaize/komodod-ac:0.1
    environment:
      - AC_NAME=TESTKMD
    command:
      -printtoconsole
      -txindex=1
      -rpcuser=test
      -rpcpassword=net
      -ac_supply=257142857
      -gen
    volumes:
      - testkomodo-data:/home/komodo/.komodo
      - zcash-params:/home/komodo/.zcash-params


  komodo-core-peer:
    extends:
      file: ../mainnet/docker-compose.yml
      service: komodo-core
    image: monaize/komodod-ac:0.1
    networks:
      - rpc
    ports:
      - 10783
    environment:
      - AC_NAME=TESTKMD
    command:
      -printtoconsole
      -ac_supply=257142857
      -txindex=1
      -server=1
      -rpcuser=test
      -rpcpassword=net
      -rpcallowip=172.0.0.0/8
      -rpcport=10783
      -addnode=komodo-core
    volumes:
      - zcash-params:/home/komodo/.zcash-params


  electrum:
    image: monaize/electrumx:latest
    networks:
      - rpc
      - ext
    ports:
      - 50001
      - 50002
    environment:
      - DAEMON_URL=http://test:net@komodo-core-peer:10783/
      - TCP_PORT=50001
      - SSL_PORT=50002
      - RPC_PORT=8000
      - COIN=TestKomodo
    volumes:
      - electrumx-testkomodo-data:/data

volumes:
  testkomodo-data:
  # testkomodo-peer-data:
  electrumx-testkomodo-data:
  zcash-params:
    external: true

networks:
  ext:
    external: true
  p2p:
  rpc: