version: '2.1'

services:
  komodo-core:
    image: monaize/komodo-ac:latest
    environment:
      - AC_NAME=MNZ
    networks:
      - p2p
    command:
      -printtoconsole=1
      -rpcallowip=172.0.0.0/8
      -server=1
      -txindex=1
      -rpcuser=main
      -rpcpassword=net
      -addnode=51.15.138.138
      -addnode=51.15.86.136
      -addnode=51.15.94.249
      -addnode=51.15.80.18
      -addnode=51.15.91.40
      -addnode=51.15.54.2
      -addnode=51.15.86.31
      -addnode=51.15.82.29
      -addnode=51.15.89.155
      -addnode=51.15.202.191
      -ac_supply=257142858
    volumes:
      - komodo-data:/home/komodo/.komodo
      - zcash-params:/home/komodo/.zcash-params

  electrumx:
    image: monaize/electrumx:latest
    networks:
      - rpc
      - ext
    ports:
      - 50001
      - 50002
    environment:
      - DAEMON_URL=http://main:net@komodo-core:14337/
      - TCP_PORT=50001
      - SSL_PORT=50002
      - RPC_PORT=8000
      - COIN=Monaize
    volumes:
      - electrumx-komodo-data:/data

volumes:
  komodo-data:
  electrumx-komodo-data:
  zcash-params:
    external: true

networks:
  ext:
    external: true
  p2p:
  rpc: