version: '2.1'

services:
  komodo-core:
    image: monaize/komodo:latest
    networks:
      - p2p
    command:
      -printtoconsole=1
      -rpcallowip=172.0.0.0/8
      -server=1
      -txindex=1
      -rpcuser=main
      -rpcpassword=net
      -addnode=5.9.102.210
      -addnode=78.47.196.146
      -addnode=178.63.69.164
      -addnode=88.198.65.74
      -addnode=5.9.122.241
      -addnode=144.76.94.38
      -addnode=89.248.166.91
    volumes:
      - komodo-data:/home/komodo/.komodo
      - zcash-params:/home/komodo/.zcash-params

  electrumx:
    image: lukechilds/electrumx:v1.4
    networks:
      - rpc
      - ext
    ports:
      - 50001
      - 50002
    environment:
      - DAEMON_URL=http://test:net@komodo-core:7771/
      - TCP_PORT=50001
      - SSL_PORT=50002
      - RPC_PORT=8000
      - COIN=Komodo
    volumes:
      - electrumx-komodo-data:/data

volumes:
  komodo-data:
  electrumx-komodo-data:
  zcash-params:
    external: true

networks:
  ext:
    external: true
  p2p:
  rpc: