version: '2.1'

services:
  bitcoin-core:
    image: ruimarinho/bitcoin-core:0.16.0-alpine
    ports:
      - 8333:8333
    networks:
      - p2p
      - rpc
    command:
      -printtoconsole
      -txindex=1
      -rpcallowip=172.0.0.0/8
      -rpcuser=main
      -rpcpassword=net
    volumes:
      - bitcoin-data:/home/bitcoin/.bitcoin

  electrumx:
    image: lukechilds/electrumx:v1.4
    networks:
      - rpc
      - ext
    ports:
      - 10000:50001
      - 20000:50002
    environment:
      - DAEMON_URL=http://main:net@bitcoin-core:8332/
      - TCP_PORT=50001
      - SSL_PORT=50002
      - RPC_PORT=8000
      - COIN=BitcoinSegwit
    volumes:
      - electrumx-bitcoin-data:/data

volumes:
  bitcoin-data:
  electrumx-bitcoin-data:

networks:
  ext:
    external: true
  p2p:
  rpc:
