version: '2.1'

services:
  bitcoin-core:
    extends:
      file: ../mainnet/docker-compose.yml
      service: bitcoin-core
    ports:
      - 18332
    command:
      -printtoconsole
      -testnet=1
      -txindex=1
      -server=1
      -rpcallowip=172.0.0.0/8
      -rpcuser=test
      -rpcpassword=net
    volumes:
      - bitcoin-testnet-data:/home/bitcoin/.bitcoin

  electrumx:
    extends:
      file: ../mainnet/docker-compose.yml
      service: electrumx
    environment:
      - DAEMON_URL=http://test:net@bitcoin-core:18332/
      - NET=testnet
    volumes:
      - electrumx-bitcoin-testnet-data:/data

volumes:
  bitcoin-testnet-data:
  electrumx-bitcoin-testnet-data:

networks:
  ext:
    external: true
  p2p:
  rpc: